name: Lint, Format, and Test for Frontend

on:
  push:
    branches: [mainnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn]
    paths:
      - "**"
      - "!music_data/**"
      - "music_data/**/*.md"
  pull_request:
    branches: [mainnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn]
    paths:
      - "**"
      - "!music_data/**"
      - "music_data/**/*.md"

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format

      - name: Run tests
        run: npm run test
